package:
  name: r-devemf
  version: 3.6.3

source:
  url:  	http://repo.continuum.io/pkgs/r/win-64/r-devemf-3.6_3-r36h796a38f_0.tar.bz2
  sha256: 1e8edda85318f27ceb5cd073c94da97406888e45f5f2e53f3e177cddbd3362bd

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-devEMF", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base
    - r-devtools
    - r-tidyverse

  run:
    - r-base
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(devEMF)"

about:
  home: https://github.com/plfjohnson/devEMF
  license: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary:  R package to produce EMF and EMF+ vector graphics 

extra:
  recipe-maintainers:
    - Fabian-Boehm
