package:
  name: r-devemf
  version: 3.6.3

source:
  url: http://repo.continuum.io/pkgs/r/linux-64/r-devemf-3.6_3-r36h29659fb_0.tar.bz2 # [linux and aarch64]
  sha256: 1c51c46dccb898c68d4f905af76329ab330594d8b0dfc288bfb441410175686f 

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-devEMF", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base
    - r-devtools
    - r-tidyverse

  run:
    - r-base
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(devEMF)"

about:
  home: https://github.com/plfjohnson/devEMF
  license: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary:  R package to produce EMF and EMF+ vector graphics 

extra:
  additional-platforms:
    -linux-aarch64
  recipe-maintainers:
    - Fabian-Boehm
