package:
  name: r-devemf
  version: 3.6.3

source:
  url: https://github.com/cran/devEMF/archive/refs/tags/3.6-3.tar.gz
  sha256: 4242863328bd13250d1dbe20812c80c5c080b10c0e6a6b4603fc5ac44aa62ec1

build:
  number: 0
  run_exports: '{{ pin_compatible("r-devEMF", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base
    - r-devtools
    - r-tidyverse

  run:
    - r-base
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(devEMF)"

about:
  home: https://github.com/plfjohnson/devEMF
  license: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary:  R package to produce EMF and EMF+ vector graphics 

extra:
  additional-platforms:
    -linux-aarch64
  recipe-maintainers:
    - Fabian-Boehm
  skip-lints:
    - should_be_noarch_generic
