package:
  name: r-devemf
  version: 4.1

source:
  url: https://github.com/plfjohnson/devEMF/archive/refs/tags/v4.1.2.tar.gz
  sha256: 8dcdc7cfd53fe453abe9df81253078899f9496bfc0b65a195d59206545cec2da

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-devEMF", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base
    - r-devtools
    - r-tidyverse

  run:
    - r-base
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(devEMF)"

about:
  home: https://github.com/plfjohnson/devEMF
  license: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3
  summary:  R package to produce EMF and EMF+ vector graphics 

extra:
  recipe-maintainers:
    - Fabian-Boehm
