package:
  name: r-seqrflp
  version: 1.0.1

source:
  url: https://cran.r-project.org/src/contrib/Archive/seqRFLP/seqRFLP_1.0.1.tar.gz
  sha256: 734f3e5f38f8178629f13d0b4b7819f675105314fe0cd1a05928f3c7518528c5

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-seqrflp", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base =3.6.3
    - r-devtools
    - r-tidyverse

  run:
    - r-base =3.6.3
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(seqRFLP)"

about:
  home: https://github.com/helixcn/seqRFLP
  license: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2
  summary:  Simulation and visualization of restriction enzyme cutting pattern from DNA sequences 

extra:
  recipe-maintainers:
    - Fabian-Boehm
