package:
  name: r-movapa
  version: 0.2.0

source:
  url: https://github.com/BMILAB/movAPA/archive/refs/heads/master.zip
  sha256: cedc9ba4fe1abfc4d0e116a55ac74a6541dc2d59c5cf920bbef296d6451fc8a7

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-polyatailor", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base =3.6.3
    - r-devtools
    - r-tidyverse

  run:
    - r-base =3.6.3
    - r-devtools
    - r-tidyverse

test:
  commands:
    - $R -e "library(PolyAtailor)"

about:
  home: https://github.com/BMILAB/movAPA
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: This package provides functions for modeling and visualization of dynamics of alternative polyadenylation acros

extra:
  additional-platforms:
    - osx-arm64
  identifiers:
    - doi:10.1093/bioinformatics/btaa997
  recipe-maintainers:
    - Fabian-Boehm
