package:
  name: r-polyatailor
  version: 0.1.0

source:
  url: https://github.com/BMILAB/PolyAtailor/archive/refs/heads/master.zip
  sha256: a4b959f46860a3641c27a78ee15636a0427cf4c695ed83770fd1da181ddc2c79

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-polyatailor", max_pin="x.x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base >=4.3,<4.4.0a0
    - r-devtools
    - r-tidyverse
  run:
    - r-base
    - r-devtools
    - r-tidyverse
    - bioconductor-genomicfeatures =1.54
    - bioconductor-biostrings =2.66.0
    - r-conflicted
    - r-data.table
    - r-desctools
    - r-dplyr
    - r-eoffice
    - r-esquisse
    - bioconductor-geneanswers
    - bioconductor-genomicranges
    - r-ggally
    - r-ggplot2
    - r-ggpubr
    - r-ggsci
    - r-ggthemes
    - r-gridextra
    - r-magrittr
    - r-movapa
    - bioconductor-org.at.tair.db
    - bioconductor-org.hs.eg.db
    - bioconductor-org.mm.eg.db
    - r-plotrix
    - r-purrr
    - r-remotes
    - bioconductor-rsamtools
    - r-seqrflp
    - bioconductor-shortread
    - r-sqldf
    - r-stringi
    - r-stringr
    - r-tidyr
    - r-upsetr
    - r-venndiagram
    - bioconductor-txdb.athaliana.biomart.plantsmart28
    - bioconductor-bsgenome.athaliana.tair.tair9
    - r-rcolorbrewer
    - r-pracma

test:
  commands:
    - $R -e "library(PolyAtailor)"

about:
  home: https://github.com/BMILAB/PolyAtailor
  license: GPL-3.0
  license_file: LICENSE.txt
  summary: An R package for poly(A) tail analysis in long and short read RNA sequencing data.

extra:
  additional-platforms:
    - osx-arm64
  identifiers:
    - doi:10.1093/bib/bbac271
  recipe-maintainers:
    - Fabian-Boehm
