package:
  name: r-polyatailor
  version: 0.1.0

source:
  url: https://github.com/XHWUlab/PolyAtailor/archive/refs/heads/master.zip
  sha256: e71db7653bce563cd713eb9be604773bcd1e48c2a4b819ae353455041ccf85c3

build:
  number: 0
  noarch: generic
  run_exports: '{{ pin_compatible("r-polyatailor", max_pin="x") }}'
  rpaths:
    - lib/R/lib
    - lib

requirements:
  host:
    - r-base
    - r-devtools
    - r-tidyverse
  run:
    - r-base
    - r-devtools
    - r-tidyverse
    - r-biostrings
    - r-conflicted
    - r-data.table
    - r-desctools
    - r-dplyr
    - r-eoffice
    - r-esquisse
    - r-geneanswers
    - r-genomicranges
    - r-ggally
    - r-ggplot2
    - r-ggpubr
    - r-ggsci
    - r-ggthemes
    - r-gridextra
    - r-magrittr
    - r-movapa
    - r-org.at.tair.db
    - r-org.hs.eg.db
    - r-org.mm.eg.db
    - r-plotrix
    - r-purrr
    - r-remotes
    - r-rsamtools
    - r-seqrflp
    - r-shortread
    - r-sqldf
    - r-stringi
    - r-stringr
    - r-tidyr
    - r-upsetr
    - r-venndiagram
    - r-txdb.athaliana.biomart.plantsmart28
    - r-bsgenome.athaliana.tair.tair9
    - r-rcolorbrewer
    - r-pracma

test:
  commands:
    - $R -e "library(PolyAtailor)"

about:
  home: https://github.com/XHWUlab/PolyAtailor
  license: GPL-3
  summary: An R package for poly(A) tail analysis in long and short read RNA sequencing data.

extra:
  additional-platforms:
    - linux-aarch64
  identifiers:
    - doi: 10.1093/bib/bbac271
  recipe-maintainers:
    - Fabian-Boehm 

